version: '3.8'

services:
  db:
    image: postgres:16.3
    container_name: postgres-db
    environment:
      POSTGRES_DB: bookkeeping
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
    networks:
      - app-network
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
